apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: express-demo 
  namespace: express-demo  
spec:
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
        - express-demo
